server:
  port: 8084
  servlet:
    context-path: /pharmacy

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/mycare_pharmacy}
    driverClassName: ${DBSM_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      dialect: ${Dialect:org.hibernate.dialect.MySQL8Dialect} 
      ddl-auto: update
    show-sql: true